package com.tcz.api.model.po;

import java.math.BigDecimal;
import java.util.Date;

public class OrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_detail.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_detail.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_detail.item_id
     *
     * @mbggenerated
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_detail.order_code
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_detail.purchasel_price
     *
     * @mbggenerated
     */
    private BigDecimal purchaselPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_detail.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_detail.delete_flag
     *
     * @mbggenerated
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_detail.cloud_code
     *
     * @mbggenerated
     */
    private String cloudCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_detail.win_state
     *
     * @mbggenerated
     */
    private String winState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_detail.id
     *
     * @return the value of tcz_order_detail.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_detail.id
     *
     * @param id the value for tcz_order_detail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_detail.order_id
     *
     * @return the value of tcz_order_detail.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_detail.order_id
     *
     * @param orderId the value for tcz_order_detail.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_detail.item_id
     *
     * @return the value of tcz_order_detail.item_id
     *
     * @mbggenerated
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_detail.item_id
     *
     * @param itemId the value for tcz_order_detail.item_id
     *
     * @mbggenerated
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_detail.order_code
     *
     * @return the value of tcz_order_detail.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_detail.order_code
     *
     * @param orderCode the value for tcz_order_detail.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_detail.purchasel_price
     *
     * @return the value of tcz_order_detail.purchasel_price
     *
     * @mbggenerated
     */
    public BigDecimal getPurchaselPrice() {
        return purchaselPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_detail.purchasel_price
     *
     * @param purchaselPrice the value for tcz_order_detail.purchasel_price
     *
     * @mbggenerated
     */
    public void setPurchaselPrice(BigDecimal purchaselPrice) {
        this.purchaselPrice = purchaselPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_detail.create_time
     *
     * @return the value of tcz_order_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_detail.create_time
     *
     * @param createTime the value for tcz_order_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_detail.modify_time
     *
     * @return the value of tcz_order_detail.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_detail.modify_time
     *
     * @param modifyTime the value for tcz_order_detail.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_detail.delete_flag
     *
     * @return the value of tcz_order_detail.delete_flag
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_detail.delete_flag
     *
     * @param deleteFlag the value for tcz_order_detail.delete_flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_detail.cloud_code
     *
     * @return the value of tcz_order_detail.cloud_code
     *
     * @mbggenerated
     */
    public String getCloudCode() {
        return cloudCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_detail.cloud_code
     *
     * @param cloudCode the value for tcz_order_detail.cloud_code
     *
     * @mbggenerated
     */
    public void setCloudCode(String cloudCode) {
        this.cloudCode = cloudCode == null ? null : cloudCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_detail.win_state
     *
     * @return the value of tcz_order_detail.win_state
     *
     * @mbggenerated
     */
    public String getWinState() {
        return winState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_detail.win_state
     *
     * @param winState the value for tcz_order_detail.win_state
     *
     * @mbggenerated
     */
    public void setWinState(String winState) {
        this.winState = winState == null ? null : winState.trim();
    }
}