package com.tcz.api.model.po;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * id
     */
    private Long id;

    /**
     * 订单编号
     */
    
    private String code;

    /**
     * 订单状态 0：未审核,1：已确认,2：已配货,3：已发货,4：已收货，5：已完成，6：待评价，7已关闭
     */
    private String status;

    /**
     * 收货人地址id
     */
    private Long userAddressid;

    /**
     * 收货人详细地址
     */
    private String addressDetail;

    /**
     * 收货人姓名
     */
    private String receiveName;

    /**
     * 收货人联系方式
     */
    private String receiveTell;

    /**
     * 邮编
     */
    private String zipCode;

    /**
     * 配送方式
     */
    private String shipType;

    /**
     * 支付方式
     */
    private String payType;

    /**
     * 是否开票
     */
    private String isInvoice;

    /**
     * 开票信息
     */
    private String invoiceInfo;

    /**
     * 备注
     */
    private String comment;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 最后修改时间
     */
    private Date modifyTime;

    /**
     * 删除标识
     */
    private String deleteFlag;


    /**
     * 支付金额
     */
    private Long payAmount;

    /**
     * 支付状态 0：未支付，1已支付
     */
    private String payStatus;

    /**
     * 评价等级
     */
    private String evaluateLevel;

    /**
     * 是否中奖 0：未中奖，1中奖
     */
    private String winState;

    /**
     * 会员id
     */
    private Long memberId;

    /**
     * 运费
     */
    private BigDecimal freight;

    /**
     * 折扣金额 
     */
    private BigDecimal couponDiscount;

    /**
     * 评价内容
     */
    private String evaluateContent;
    
    /**
     * 期数
     */
    private Long periods;

    /**
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.id
     *
     * @param id the value for tcz_order.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.code
     *
     * @return the value of tcz_order.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.code
     *
     * @param code the value for tcz_order.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.status
     *
     * @return the value of tcz_order.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.status
     *
     * @param status the value for tcz_order.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.user_addressId
     *
     * @return the value of tcz_order.user_addressId
     *
     * @mbggenerated
     */
    public Long getUserAddressid() {
        return userAddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.user_addressId
     *
     * @param userAddressid the value for tcz_order.user_addressId
     *
     * @mbggenerated
     */
    public void setUserAddressid(Long userAddressid) {
        this.userAddressid = userAddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.address_Detail
     *
     * @return the value of tcz_order.address_Detail
     *
     * @mbggenerated
     */
    public String getAddressDetail() {
        return addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.address_Detail
     *
     * @param addressDetail the value for tcz_order.address_Detail
     *
     * @mbggenerated
     */
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail == null ? null : addressDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.receive_Name
     *
     * @return the value of tcz_order.receive_Name
     *
     * @mbggenerated
     */
    public String getReceiveName() {
        return receiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.receive_Name
     *
     * @param receiveName the value for tcz_order.receive_Name
     *
     * @mbggenerated
     */
    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName == null ? null : receiveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.receive_tell
     *
     * @return the value of tcz_order.receive_tell
     *
     * @mbggenerated
     */
    public String getReceiveTell() {
        return receiveTell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.receive_tell
     *
     * @param receiveTell the value for tcz_order.receive_tell
     *
     * @mbggenerated
     */
    public void setReceiveTell(String receiveTell) {
        this.receiveTell = receiveTell == null ? null : receiveTell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.zip_code
     *
     * @return the value of tcz_order.zip_code
     *
     * @mbggenerated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.zip_code
     *
     * @param zipCode the value for tcz_order.zip_code
     *
     * @mbggenerated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.ship_type
     *
     * @return the value of tcz_order.ship_type
     *
     * @mbggenerated
     */
    public String getShipType() {
        return shipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.ship_type
     *
     * @param shipType the value for tcz_order.ship_type
     *
     * @mbggenerated
     */
    public void setShipType(String shipType) {
        this.shipType = shipType == null ? null : shipType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.pay_type
     *
     * @return the value of tcz_order.pay_type
     *
     * @mbggenerated
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.pay_type
     *
     * @param payType the value for tcz_order.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.is_Invoice
     *
     * @return the value of tcz_order.is_Invoice
     *
     * @mbggenerated
     */
    public String getIsInvoice() {
        return isInvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.is_Invoice
     *
     * @param isInvoice the value for tcz_order.is_Invoice
     *
     * @mbggenerated
     */
    public void setIsInvoice(String isInvoice) {
        this.isInvoice = isInvoice == null ? null : isInvoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.invoice_Info
     *
     * @return the value of tcz_order.invoice_Info
     *
     * @mbggenerated
     */
    public String getInvoiceInfo() {
        return invoiceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.invoice_Info
     *
     * @param invoiceInfo the value for tcz_order.invoice_Info
     *
     * @mbggenerated
     */
    public void setInvoiceInfo(String invoiceInfo) {
        this.invoiceInfo = invoiceInfo == null ? null : invoiceInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.comment
     *
     * @return the value of tcz_order.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.comment
     *
     * @param comment the value for tcz_order.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.create_time
     *
     * @return the value of tcz_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.create_time
     *
     * @param createTime the value for tcz_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.modify_time
     *
     * @return the value of tcz_order.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.modify_time
     *
     * @param modifyTime the value for tcz_order.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.delete_flag
     *
     * @return the value of tcz_order.delete_flag
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.delete_flag
     *
     * @param deleteFlag the value for tcz_order.delete_flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.pay_amount
     *
     * @return the value of tcz_order.pay_amount
     *
     * @mbggenerated
     */
    public Long getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.pay_amount
     *
     * @param payAmount the value for tcz_order.pay_amount
     *
     * @mbggenerated
     */
    public void setPayAmount(Long payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.pay_status
     *
     * @return the value of tcz_order.pay_status
     *
     * @mbggenerated
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.pay_status
     *
     * @param payStatus the value for tcz_order.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.evaluate_level
     *
     * @return the value of tcz_order.evaluate_level
     *
     * @mbggenerated
     */
    public String getEvaluateLevel() {
        return evaluateLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.evaluate_level
     *
     * @param evaluateLevel the value for tcz_order.evaluate_level
     *
     * @mbggenerated
     */
    public void setEvaluateLevel(String evaluateLevel) {
        this.evaluateLevel = evaluateLevel == null ? null : evaluateLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.win_state
     *
     * @return the value of tcz_order.win_state
     *
     * @mbggenerated
     */
    public String getWinState() {
        return winState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.win_state
     *
     * @param winState the value for tcz_order.win_state
     *
     * @mbggenerated
     */
    public void setWinState(String winState) {
        this.winState = winState == null ? null : winState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.member_id
     *
     * @return the value of tcz_order.member_id
     *
     * @mbggenerated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.member_id
     *
     * @param memberId the value for tcz_order.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.evaluate_content
     *
     * @return the value of tcz_order.evaluate_content
     *
     * @mbggenerated
     */
    public String getEvaluateContent() {
        return evaluateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.evaluate_content
     *
     * @param evaluateContent the value for tcz_order.evaluate_content
     *
     * @mbggenerated
     */
    public void setEvaluateContent(String evaluateContent) {
        this.evaluateContent = evaluateContent == null ? null : evaluateContent.trim();
    }

	public BigDecimal getFreight() {
		return freight;
	}

	public void setFreight(BigDecimal freight) {
		this.freight = freight;
	}

	public BigDecimal getCouponDiscount() {
		return couponDiscount;
	}

	public void setCouponDiscount(BigDecimal couponDiscount) {
		this.couponDiscount = couponDiscount;
	}

	/**
	 * @return the period
	 */
	public Long getPeriod() {
		return periods;
	}

	/**
	 * @param period the period to set
	 */
	public void setPeriod(Long periods) {
		this.periods = periods;
	}
    
}