package com.tcz.api.model;

import java.util.Date;

public class OrderLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_log.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_log.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_log.delete_flag
     *
     * @mbggenerated
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order_log.change_log
     *
     * @mbggenerated
     */
    private String changeLog;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_log.id
     *
     * @return the value of tcz_order_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_log.id
     *
     * @param id the value for tcz_order_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_log.order_id
     *
     * @return the value of tcz_order_log.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_log.order_id
     *
     * @param orderId the value for tcz_order_log.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_log.create_time
     *
     * @return the value of tcz_order_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_log.create_time
     *
     * @param createTime the value for tcz_order_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_log.modify_time
     *
     * @return the value of tcz_order_log.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_log.modify_time
     *
     * @param modifyTime the value for tcz_order_log.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_log.delete_flag
     *
     * @return the value of tcz_order_log.delete_flag
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_log.delete_flag
     *
     * @param deleteFlag the value for tcz_order_log.delete_flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order_log.change_log
     *
     * @return the value of tcz_order_log.change_log
     *
     * @mbggenerated
     */
    public String getChangeLog() {
        return changeLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order_log.change_log
     *
     * @param changeLog the value for tcz_order_log.change_log
     *
     * @mbggenerated
     */
    public void setChangeLog(String changeLog) {
        this.changeLog = changeLog == null ? null : changeLog.trim();
    }
}