package com.tcz.api.mapper;

import com.tcz.api.model.po.OrderLog;

public interface OrderLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcz_order_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcz_order_log
     *
     * @mbggenerated
     */
    int insert(OrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcz_order_log
     *
     * @mbggenerated
     */
    int insertSelective(OrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcz_order_log
     *
     * @mbggenerated
     */
    OrderLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcz_order_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcz_order_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcz_order_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderLog record);
}