package com.tcz.api.mapper;

import com.tcz.api.model.po.PluginConfig;

public interface PluginConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcz_plugin_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcz_plugin_config
     *
     * @mbggenerated
     */
    int insert(PluginConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcz_plugin_config
     *
     * @mbggenerated
     */
    int insertSelective(PluginConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcz_plugin_config
     *
     * @mbggenerated
     */
    PluginConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcz_plugin_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PluginConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcz_plugin_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(PluginConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcz_plugin_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PluginConfig record);
}