package com.tcz.api.model.po;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.sn
     *
     * @mbggenerated
     */
    private String sn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.user_address_id
     *
     * @mbggenerated
     */
    private Long userAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.address_detail
     *
     * @mbggenerated
     */
    private String addressDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.receive_name
     *
     * @mbggenerated
     */
    private String receiveName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.receive_tell
     *
     * @mbggenerated
     */
    private String receiveTell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.zip_code
     *
     * @mbggenerated
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.ship_type
     *
     * @mbggenerated
     */
    private String shipType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.ship_no
     *
     * @mbggenerated
     */
    private String shipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.plugin_config_id
     *
     * @mbggenerated
     */
    private String pluginConfigId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.is_Invoice
     *
     * @mbggenerated
     */
    private String isInvoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.invoice_info
     *
     * @mbggenerated
     */
    private String invoiceInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.create_time
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.modify_time
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.delete_flag
     *
     * @mbggenerated
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.pay_amount
     *
     * @mbggenerated
     */
    private Long payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.pay_status
     *
     * @mbggenerated
     */
    private String payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.evaluate_level
     *
     * @mbggenerated
     */
    private String evaluateLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.member_id
     *
     * @mbggenerated
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.freight
     *
     * @mbggenerated
     */
    private BigDecimal freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.coupon_discount
     *
     * @mbggenerated
     */
    private BigDecimal couponDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.periods
     *
     * @mbggenerated
     */
    private Long periods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcz_order.evaluate_content
     *
     * @mbggenerated
     */
    private String evaluateContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.id
     *
     * @return the value of tcz_order.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.id
     *
     * @param id the value for tcz_order.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.sn
     *
     * @return the value of tcz_order.sn
     *
     * @mbggenerated
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.sn
     *
     * @param sn the value for tcz_order.sn
     *
     * @mbggenerated
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.status
     *
     * @return the value of tcz_order.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.status
     *
     * @param status the value for tcz_order.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.user_address_id
     *
     * @return the value of tcz_order.user_address_id
     *
     * @mbggenerated
     */
    public Long getUserAddressId() {
        return userAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.user_address_id
     *
     * @param userAddressId the value for tcz_order.user_address_id
     *
     * @mbggenerated
     */
    public void setUserAddressId(Long userAddressId) {
        this.userAddressId = userAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.address_detail
     *
     * @return the value of tcz_order.address_detail
     *
     * @mbggenerated
     */
    public String getAddressDetail() {
        return addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.address_detail
     *
     * @param addressDetail the value for tcz_order.address_detail
     *
     * @mbggenerated
     */
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail == null ? null : addressDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.receive_name
     *
     * @return the value of tcz_order.receive_name
     *
     * @mbggenerated
     */
    public String getReceiveName() {
        return receiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.receive_name
     *
     * @param receiveName the value for tcz_order.receive_name
     *
     * @mbggenerated
     */
    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName == null ? null : receiveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.receive_tell
     *
     * @return the value of tcz_order.receive_tell
     *
     * @mbggenerated
     */
    public String getReceiveTell() {
        return receiveTell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.receive_tell
     *
     * @param receiveTell the value for tcz_order.receive_tell
     *
     * @mbggenerated
     */
    public void setReceiveTell(String receiveTell) {
        this.receiveTell = receiveTell == null ? null : receiveTell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.zip_code
     *
     * @return the value of tcz_order.zip_code
     *
     * @mbggenerated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.zip_code
     *
     * @param zipCode the value for tcz_order.zip_code
     *
     * @mbggenerated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.ship_type
     *
     * @return the value of tcz_order.ship_type
     *
     * @mbggenerated
     */
    public String getShipType() {
        return shipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.ship_type
     *
     * @param shipType the value for tcz_order.ship_type
     *
     * @mbggenerated
     */
    public void setShipType(String shipType) {
        this.shipType = shipType == null ? null : shipType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.ship_no
     *
     * @return the value of tcz_order.ship_no
     *
     * @mbggenerated
     */
    public String getShipNo() {
        return shipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.ship_no
     *
     * @param shipNo the value for tcz_order.ship_no
     *
     * @mbggenerated
     */
    public void setShipNo(String shipNo) {
        this.shipNo = shipNo == null ? null : shipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.plugin_config_id
     *
     * @return the value of tcz_order.plugin_config_id
     *
     * @mbggenerated
     */
    public String getPluginConfigId() {
        return pluginConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.plugin_config_id
     *
     * @param pluginConfigId the value for tcz_order.plugin_config_id
     *
     * @mbggenerated
     */
    public void setPluginConfigId(String pluginConfigId) {
        this.pluginConfigId = pluginConfigId == null ? null : pluginConfigId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.is_Invoice
     *
     * @return the value of tcz_order.is_Invoice
     *
     * @mbggenerated
     */
    public String getIsInvoice() {
        return isInvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.is_Invoice
     *
     * @param isInvoice the value for tcz_order.is_Invoice
     *
     * @mbggenerated
     */
    public void setIsInvoice(String isInvoice) {
        this.isInvoice = isInvoice == null ? null : isInvoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.invoice_info
     *
     * @return the value of tcz_order.invoice_info
     *
     * @mbggenerated
     */
    public String getInvoiceInfo() {
        return invoiceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.invoice_info
     *
     * @param invoiceInfo the value for tcz_order.invoice_info
     *
     * @mbggenerated
     */
    public void setInvoiceInfo(String invoiceInfo) {
        this.invoiceInfo = invoiceInfo == null ? null : invoiceInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.comment
     *
     * @return the value of tcz_order.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.comment
     *
     * @param comment the value for tcz_order.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.create_time
     *
     * @return the value of tcz_order.create_time
     *
     * @mbggenerated
     */
    public Date getcreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.create_time
     *
     * @param createDate the value for tcz_order.create_time
     *
     * @mbggenerated
     */
    public void setcreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.modify_time
     *
     * @return the value of tcz_order.modify_time
     *
     * @mbggenerated
     */
    public Date getmodifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.modify_time
     *
     * @param modifyDate the value for tcz_order.modify_time
     *
     * @mbggenerated
     */
    public void setmodifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.delete_flag
     *
     * @return the value of tcz_order.delete_flag
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.delete_flag
     *
     * @param deleteFlag the value for tcz_order.delete_flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.pay_amount
     *
     * @return the value of tcz_order.pay_amount
     *
     * @mbggenerated
     */
    public Long getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.pay_amount
     *
     * @param payAmount the value for tcz_order.pay_amount
     *
     * @mbggenerated
     */
    public void setPayAmount(Long payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.pay_status
     *
     * @return the value of tcz_order.pay_status
     *
     * @mbggenerated
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.pay_status
     *
     * @param payStatus the value for tcz_order.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.evaluate_level
     *
     * @return the value of tcz_order.evaluate_level
     *
     * @mbggenerated
     */
    public String getEvaluateLevel() {
        return evaluateLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.evaluate_level
     *
     * @param evaluateLevel the value for tcz_order.evaluate_level
     *
     * @mbggenerated
     */
    public void setEvaluateLevel(String evaluateLevel) {
        this.evaluateLevel = evaluateLevel == null ? null : evaluateLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.member_id
     *
     * @return the value of tcz_order.member_id
     *
     * @mbggenerated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.member_id
     *
     * @param memberId the value for tcz_order.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.freight
     *
     * @return the value of tcz_order.freight
     *
     * @mbggenerated
     */
    public BigDecimal getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.freight
     *
     * @param freight the value for tcz_order.freight
     *
     * @mbggenerated
     */
    public void setFreight(BigDecimal freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.coupon_discount
     *
     * @return the value of tcz_order.coupon_discount
     *
     * @mbggenerated
     */
    public BigDecimal getCouponDiscount() {
        return couponDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.coupon_discount
     *
     * @param couponDiscount the value for tcz_order.coupon_discount
     *
     * @mbggenerated
     */
    public void setCouponDiscount(BigDecimal couponDiscount) {
        this.couponDiscount = couponDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.periods
     *
     * @return the value of tcz_order.periods
     *
     * @mbggenerated
     */
    public Long getPeriods() {
        return periods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.periods
     *
     * @param periods the value for tcz_order.periods
     *
     * @mbggenerated
     */
    public void setPeriods(Long periods) {
        this.periods = periods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcz_order.evaluate_content
     *
     * @return the value of tcz_order.evaluate_content
     *
     * @mbggenerated
     */
    public String getEvaluateContent() {
        return evaluateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcz_order.evaluate_content
     *
     * @param evaluateContent the value for tcz_order.evaluate_content
     *
     * @mbggenerated
     */
    public void setEvaluateContent(String evaluateContent) {
        this.evaluateContent = evaluateContent == null ? null : evaluateContent.trim();
    }
}